### ISSUE TITLE
✨ 연금저축 및 IRP 컴포넌트에 유저 데이터 적용 

### ISSUE THREAD

**Issue by youhyeoneee** [13th-month-lucky/frontend#17]
## 📌 Description
- 컴포넌트 내에 임시로 초기화한 데이터들을 유저 데이터로 적용하기 

## 📝 To-do
- [x] 유저의 남은 돈 (현재는 500,000원으로 초기화 되어있음)
- [x] 유저의 납입액 (현재는 0원으로 초기화 되어있음)
- [x] 유저의 납입액에 따른 한도 계산식 적용하기
- [x] 유저 미가입 시 문구 변경
- [x] 실제 유저 DB 데이터 연동
- [x] 솔루션 총 금액에도 더해지게
