### ISSUE TITLE
✨월세 컴포넌트 개발

### ISSUE THREAD

**Issue by youhyeoneee** [13th-month-lucky/frontend#18]
## 📌 Description
- 월세 컴포넌트 개발

## 📝 To-do
- [x] 이미지 및 텍스트 
- [x] 무주택 세대 해당 여부 check box
- [x] 월세 금액 input box
- [x] 디자인 피그마와 동일하게 적용
