### ISSUE TITLE
♻️ 디자인 통일 및 다듬는 작업

### ISSUE THREAD

**Issue by youhyeoneee** [13th-month-lucky/frontend#28]
## 📌 Description
- preview 페이지 내 모든 컴포넌트 디자인 통일 
- 그 외 디자인 테마 css 클래스 따로 빼기

## 📝 To-do
- [x] preview 페이지 내 컴포넌트 디자인 통일
   - [x] 글씨체 : 두께, 색상
- [x] preview main, result 마진 탑 올리기
- [x] loading -> result : timeout 적용 @allllfo 
- [x] 글씨체 변경
- [x] 블루 버튼 컴포넌트 생성
- [x] 로고 넣기
