### ISSUE TITLE
✨연말정산 페이지 디테일

### ISSUE THREAD

**Issue by youhyeoneee** [13th-month-lucky/frontend#68]
## 📌 Description
- 

## 📝 To-do
- [x] 솔루션 이행 시 아낄 수 있는 금액 위에 고정
- [ ] 각 공제 금액 표시 위치 통일 - 어떻게 잘보이게 할까
- [x] 인적 공제 + - 위치 변경
- [ ] 카드 공제 도움말 > 뒤 공백 통일 
- [ ] 돈 표기 숫자 -> 한글로 변경할 지 고민하기
