### ISSUE TITLE
✨ETF, 펀드 페이지 디테일

### ISSUE THREAD

**Issue by youhyeoneee** [13th-month-lucky/frontend#96]
## 📌 Description
- 

## 📝 To-do
- [x] 상위 뒤로가기 바에 제목
- [x] 탭 바 동일하게
- [x] 카드 UI 비슷하게
- [x] 관심, 최근 없을 경우 없는 이미지?나 문구 보여주기 @seungtoctoc
